FROM node:12 AS build-stage

WORKDIR /example
COPY package.json ./
COPY yarn.lock ./
# RUN yarn config set registry 'https://registry.npm.taobao.org'
# RUN yarn config set registry 'https://registry.npmjs.org/'

RUN yarn install --production
COPY . .

FROM build-stage AS prod-stage
WORKDIR /example
RUN yarn add -D @vue/cli-service
RUN yarn build
COPY ./dist ./dist
