version: '3.7'

services:
  api:
    build:
      context: ./api
      target: dev-stage
    volumes:
      - './api:/api'
      - './shared:/api/node_modules/@eduvault/shared'
      - './shared:/shared'
      - '/api/node_modules'

    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    env_file:
      - ./.env
    ports:
      - '3003:3003'
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    name: mongo
