version: '3.7'
services:
  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - '.app:/app'
      - '/app/node_modules'

  api:
    container_name: api
    build:
      context: ./api
    volumes:
      - './api:/api'
      - '/api/node_modules'
    ports:
      - '3000:3000'
