version: '3.7'

services:
  api:
    build:
      context: ./api
      target: dev-stage
    volumes:
      - './api:/api'
      - '/api/node_modules'
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    networks:
      - app-network

volumes:
  mongo:
    name: mongo

networks:
  app-network:
    name: app-network
