version: '3.7'

services:
  api:
    build:
      context: ./api
      target: dev-stage
    volumes:
      - './api:/api'
      - './shared:/api/node_modules/@eduvault/shared'
      - './shared:/shared'
      - '/api/node_modules'

    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    env_file:
      - ./.env
    ports:
      - '3003:3003'

