version: '3.7'
services:
  # app:
  #   container_name: app
  #   image: docker.io/eduvault/eduvault_app:testing
  #   expose:
  #     - 8081
  #   environment:
  #     - NODE_ENV=production
  #     - VIRTUAL_HOST=app.localhost
  #     - VIRTUAL_PORT=8081

  # example:
  #   container_name: example
  #   image: docker.io/eduvault/eduvault_example:testing
  #   expose:
  #     - 8082
  #   environment:
  #     - NODE_ENV=production
  #     - VIRTUAL_HOST=example.localhost
  #     - VIRTUAL_PORT=8082

  # api:
  #   container_name: api
  #   image: docker.io/eduvault/eduvault_api:testing
  #   expose:
  #     - 30333
  #   environment:
  #     - NODE_ENV=production
  #     - VIRTUAL_HOST=api.localhost
  #     - VIRTUAL_PORT=30333
  #     - APP_SECRET='testing-secret'
  #     - TESTING=true

  home-page:
    container_name: home-page
    image: docker.io/eduvault/eduvault_home-page:testing
    expose:
      - 8083
    environment:
      - NODE_ENV=production
      - VUE_APP_PROD_HOST=localhost
      - VIRTUAL_HOST=home.localhost,localhost
      - VIRTUAL_PORT=8083

  nginx-proxy:
    container_name: nginx-proxy
    # using this instead of jwilder because issue with m1 https://github.com/nginx-proxy/nginx-proxy/issues/1550#issuecomment-799705715
    # image: ninanung/nginx-proxy # on mac m1
    image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'
    depends_on:
      # - app
      # - api
      # - example
      - home-page
