version: '3.7'
services:
  app:
    container_name: app
    # image: docker.io/jewcub/eduvault_app:latest
    build:
      context: ./app
      target: prod-stage
      dockerfile: Dockerfile_prod
      args:
        - PROD_HOST=${PROD_HOST}
    env_file: ./.env
    ports:
      - 8081
    environment:
      - VIRTUAL_HOST=app.${PROD_HOST}
      - VIRTUAL_PORT=8081

  example:
    container_name: example
    # image: docker.io/jewcub/eduvault_example:latest
    build:
      context: ./example
      target: prod-stage
      dockerfile: Dockerfile_prod
      args:
        - PROD_HOST=${PROD_HOST}
    env_file:
      - ./.env
    ports:
      - 8082
    environment:
      - VIRTUAL_HOST=example.${PROD_HOST}
      - VIRTUAL_PORT=8082

  api:
    container_name: api
    # image: docker.io/jewcub/eduvault_api:latest
    build:
      context: ./api
      target: prod-stage
      dockerfile: Dockerfile_prod
    ports:
      - 3003
    env_file: ./.env
    environment:
      - VIRTUAL_HOST=api.${PROD_HOST}
      - VIRTUAL_PORT=3003

  home-page:
    container_name: home-page
    # image: docker.io/jewcub/eduvault_home-page:latest
    build:
      context: ./home-page
      target: prod-stage
      dockerfile: Dockerfile_prod
    ports:
      - 8083
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=home.${PROD_HOST}
      - VIRTUAL_PORT=8083

  nginx:
    container_name: nginx-proxy
    # using this instead of jwilder because issue with m1 https://github.com/nginx-proxy/nginx-proxy/issues/1550#issuecomment-799705715
    # image: ninanung/nginx-proxy # on mac m1
    image: jwilder/nginx-proxy
    # restart with: docker exec -it nginx-proxy nginx -s reload
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./deploy/dev-certs:/etc/nginx/certs:ro
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
      - api
      - example
      - home-page
