version: '3.7'
services:
  app:
    image: docker.io/jewcub/eduvault_app
    volumes:
      - dist-share:/app/dist
      - './app:/app'
      - '/app/node_modules'
    stdin_open: true
    env_file: 
      ./.env
    environment:
      - NODE_ENV=production
  example:
    image: docker.io/jewcub/eduvault_example
    volumes:
      - example-dist-share:/app/dist
      - './example:/example'
      - '/example/node_modules'
    stdin_open: true
    env_file:
      - ./.env        
    environment:
      - NODE_ENV=production
  api:
    image: docker.io/jewcub/eduvault_api
    ports:
      - '3003:3003'
    volumes:
      - './api:/api'
      - '/api/node_modules'
    env_file: 
      ./.env
    environment:
      - NODE_ENV=production

  home-page:
    image: docker.io/jewcub/eduvault_home-page
    volumes:
      - './home-page:/home-page'
      - '/home-page/node_modules'
    ports:
      - '8083:8083'
    env_file: 
      ./.env      
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./deploy/nginx/dev-build:/etc/nginx/conf.d
      - dist-share:/var/www/app-dist
      - example-dist-share:/var/www/example-dist
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
      - api
      - example
      - home-page
volumes:
  dist-share:
    driver: local
  example-dist-share:
    driver: local
