# digital ocean deploy requires certs to be generated and stored in the right folder before using
version: '3.7'
services:
  app:
    container_name: app
    image: docker.io/eduvault/eduvault_app:staging
    env_file: ./.env
    ports:
      - 8081
    environment:
      - VIRTUAL_HOST=app.${PROD_HOST}
      - VIRTUAL_PORT=8081

  example:
    container_name: example
    image: docker.io/eduvault/eduvault_example:staging
    env_file:
      - ./.env
    ports:
      - 8082
    environment:
      - VIRTUAL_HOST=example.${PROD_HOST}
      - VIRTUAL_PORT=8082

  # api:
  #   container_name: api
  #   image: docker.io/eduvault/eduvault_api:staging
  #   ports:
  #     - ${PORT_API}
  #   env_file: ./.env
  #   environment:
  #     - VIRTUAL_HOST=api.${PROD_HOST}
  #     - VIRTUAL_PORT=${PORT_API}

  home-page:
    container_name: home-page
    image: docker.io/eduvault/eduvault_home-page:staging
    ports:
      - 8083
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=home.${PROD_HOST}
      - VIRTUAL_PORT=8083

  nginx:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./deploy/prod-certs:/etc/nginx/certs:ro
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
      - api
      - example
      - home-page
