version: '3.7'
services:
  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - dist-share:/app/dist
      - './api:/app'
      - '/app/node_modules'
    stdin_open: true

  api:
    container_name: api
    build:
      context: ./api
    ports:
      - '3000:3000'
    volumes:
      - './api:/api'
      - '/api/node_modules'

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx/dev:/etc/nginx/conf.d
      - dist-share:/var/www/shared
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
      - api
volumes:
  dist-share:
    driver: local
