version: '3.7'

services:
  api:
    build:
      context: ./api
      target: dev-stage
    volumes:
      - './api:/api'
      - '/api/node_modules'
    environment:
      - NODE_ENV=development
    ports:
      - '3003:3003'
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    name: mongo
