version: '2.4'
services:
  app:
    container_name: app
    image: docker.io/eduvault/eduvault_app:testing
    expose:
      - 8081
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=app.localhost
      - VIRTUAL_PORT=8081
      - VUE_APP_TEST=1      
    # cpus: "0.2"
    # mem_limit: 212m

  example:
    container_name: example
    image: docker.io/eduvault/eduvault_example:testing
    expose:
      - 8082
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=example.localhost
      - VIRTUAL_PORT=8082
      - VUE_APP_TEST=1
    # cpus: "0.2"
    # mem_limit: 212m

  api:
    container_name: api
    image: docker.io/eduvault/eduvault_api:testing
    expose:
      - 30333
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=api.localhost
      - VIRTUAL_PORT=30333
      - TEST=1
      - PROD_HOST=localhost
    # cpus: "0.5"
    # mem_limit: 512m

  home-page:
    container_name: home-page
    image: docker.io/eduvault/eduvault_home-page:testing
    expose:
      - 8083
    environment:
      - NODE_ENV=production
      - VUE_APP_PROD_HOST=localhost
      - VIRTUAL_HOST=home.localhost,localhost
      - VIRTUAL_PORT=8083
      - TEST=1
    # cpus: "0.7"
    # mem_limit: 712m

  nginx-proxy:
    container_name: nginx-proxy
    image: ninanung/nginx-proxy # on mac m1
    # image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./deploy/dev-certs:/etc/nginx/certs:ro
    ports:
      - '80:80'
      - '443:443'      
    depends_on:
      - app
      - api
      - example
      - home-page
    # cpus: "0.2"
    # mem_limit: 512m      
