# This is the amazon elastic beanstalk deploy version. The key difference with digital ocean deploy is that in nginx-proxy we don't use ssl and port 443. ssl is handled by the load balancer.
version: '3.7'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # this will re poll for image changes every 60s, could extend in final production
    command: --interval 60

  app:
    container_name: app
    image: docker.io/eduvault/eduvault_app:latest
    env_file:
      - ./.env
    ports:
      - ${PORT_APP}
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=app.${PROD_HOST}
      - VIRTUAL_PORT=${PORT_APP}

  example:
    container_name: example
    image: docker.io/eduvault/eduvault_example:latest
    env_file:
      - ./.env
    ports:
      - ${PORT_EXAMPLE}
    expose:
      - ${PORT_EXAMPLE}
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=example.${PROD_HOST}
      - VIRTUAL_PORT=${PORT_EXAMPLE}

  api:
    container_name: api
    image: docker.io/eduvault/eduvault_api:latest
    ports:
      - ${PORT_API}
    expose:
      - ${PORT_API}
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=api.${PROD_HOST}
      - VIRTUAL_PORT=${PORT_API}

  home-page:
    container_name: home-page
    image: docker.io/eduvault/eduvault_home-page:latest
    ports:
      - ${PORT_HOME_PAGE}
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=home.${PROD_HOST}
      - VIRTUAL_PORT=${PORT_HOME_PAGE}

  nginx:
    container_name: nginx
    # image: ninanung/nginx-proxy # on mac m1
    image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'
    depends_on:
      - app
      - api
      - example
      - home-page
