version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:stable
    depends_on:
      - api
      - frontend
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: production-stage
      args:
        NODE_ENV: production
        BASE_URL: /frontend/
    depends_on:
      - api
    networks:
      - internal
    environment:
      - BASE_URL=/
      - API_URL=http://localhost/api

  api:
    container_name: api
    build:
      context: ./api
      target: production-stage
    networks:
      - internal
    environment:
      - API_URL=http://localhost/api
      - FRONTEND_URL=http://localhost/
