FROM node:12 AS build-stage
# RUN apk update
# RUN apk add git

WORKDIR /app
COPY package.json ./
# COPY yarn.lock ./
# RUN yarn config set registry 'https://registry.npm.taobao.org'
# RUN yarn config set registry 'https://registry.npmjs.org/'

RUN yarn install
COPY . .

FROM build-stage AS prod-stage
RUN yarn build

