FROM node:12 AS build-stage
ENV PATH /api/node_modules/.bin:$PATH

WORKDIR /api
COPY package.json ./
COPY yarn.lock ./api/

RUN yarn install   
COPY . .
EXPOSE 3003 

FROM build-stage AS prod-stage
ENV NODE_ENV=production

WORKDIR /api
CMD ["yarn", "prod"]
