FROM node:12-alpine AS build-stage
WORKDIR /api
COPY package*.json ./

ENV NODE_ENV=production

RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000 

FROM build-stage AS prod-stage
CMD ["npm", "run", "start"]
