FROM node:12-alpine AS build-stage
ENV PATH /api/node_modules/.bin:$PATH
RUN apk update
RUN apk add git
WORKDIR /api
COPY package.json ./
COPY yarn.lock ./

RUN yarn install
COPY . .
RUN yarn build
EXPOSE 3003 

FROM build-stage AS prod-stage
CMD ["yarn",  "start"]
