FROM node:14 AS build-stage
ENV PATH /api/node_modules/.bin:$PATH

WORKDIR /
COPY /api/package.json ./api/
COPY /api/yarn.lock ./api/

RUN yarn install
COPY ./api ./api
RUN yarn build
COPY ./.env ./api

EXPOSE 3003 

FROM build-stage AS prod-stage
CMD ["yarn",  "start"]
