name: Deployment From Github To AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@main
        
      - name: Generate Deployment Package 
        run: zip -r deploy.zip * -x "**node_modules**"
        # Just used for timestamps for versioning deployments
      - name: Get timestamp
        uses: gerred/actions/current-time@main
        id: current-time
        # Just used for timestamps - format
      - name: Run string replace
        uses: frabert/replace-string-action@main
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
          
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: eduvault
          environment_name: Eduvault-env
          version_label: "eduvault-deployment-${{ steps.format-time.outputs.replaced }}"
          region: us-east-2
          deployment_package: deploy.zip
    
