name:  Staging push Docker images
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image - api
        with:
          image: eduvault/eduvault_api
          tags: latest
          registry: docker.io
          dockerfile: api/Dockerfile_prod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image - app
        with:
          image: eduvault/eduvault_app
          tags: latest
          registry: docker.io
          dockerfile: app/Dockerfile_prod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: PROD_HOST=eduvault-staging.click

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image - example
        with:
          image: eduvault/eduvault_example
          tags: latest
          registry: docker.io
          dockerfile: example/Dockerfile_prod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
          buildArgs: PROD_HOST=eduvault-staging.click
          
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image - home-page
        with:
          image: eduvault/eduvault_home-page
          tags: latest
          registry: docker.io
          dockerfile: home-page/Dockerfile_prod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}          