name: Staging push Docker images
on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.x]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build and test
        run: |
          yarn build-run-ci
          yarn install
          yarn test:e2e
        env:
          TEXTILE_ORG_API_SECRET: ${{ secrets.TEXTILE_ORG_API_SECRET }}
          TEXTILE_USER_API_SECRET: ${{  secrets.TEXTILE_USER_API_SECRET }}
          PROD_HOST: localhost

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image - api
        with:
          image: eduvault/eduvault_api:
          tags: production
          registry: docker.io
          dockerfile: api/Dockerfile_prod
          directory: api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image - app
        with:
          image: eduvault/eduvault_app
          tags: production
          registry: docker.io
          dockerfile: app/Dockerfile_prod
          directory: app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: PROD_HOST=eduvault.org

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image - example
        with:
          image: eduvault/eduvault_example
          tags: production
          registry: docker.io
          dockerfile: example/Dockerfile_prod
          directory: example
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: PROD_HOST=eduvault.org

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image - home-page
        with:
          image: eduvault/eduvault_home-page
          tags: production
          registry: docker.io
          dockerfile: home-page/Dockerfile_prod
          directory: home-page
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
