name: Staging push Docker images
on:
  push:
    branches:
      - staging

jobs:
  test-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.13.0]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

        ##### BUILD TEST IMAGES #####
        # The point of this part is to make the test images separately on one run, then you can selectively comment out which images you want to rebuild or not. If you don't need to rebuild the images, it will make the subsequent test much faster

      # - uses: mr-smithers-excellent/docker-build-push@v5
      #   name: Build & push Docker image - api
      #   with:
      #     image: eduvault/eduvault_api
      #     tags: testing
      #     registry: docker.io
      #     dockerfile: api/Dockerfile_prod
      #     directory: api
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - uses: mr-smithers-excellent/docker-build-push@v5
      #   name: Build & push Docker image - app
      #   with:
      #     image: eduvault/eduvault_app
      #     tags: testing
      #     registry: docker.io
      #     dockerfile: app/Dockerfile_prod
      #     directory: app
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     buildArgs: PROD_HOST=localhost

      # - uses: mr-smithers-excellent/docker-build-push@v5
      #   name: Build & push Docker image - example
      #   with:
      #     image: eduvault/eduvault_example
      #     tags: testing
      #     registry: docker.io
      #     dockerfile: example/Dockerfile_prod
      #     directory: example
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     buildArgs: PROD_HOST=localhost

      # - uses: mr-smithers-excellent/docker-build-push@v5
      #   name: Build & push Docker image - home-page
      #   with:
      #     image: eduvault/eduvault_home-page
      #     tags: testing
      #     registry: docker.io
      #     dockerfile: home-page/Dockerfile_prod
      #     directory: home-page
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      ##### TEST #####

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: start app
      #   run: yarn build-run-ci
      # - name: test
      #   run: |
      #     yarn inst:e2e
      #     yarn test:e2e
      #   env:
      #     TEST: 1
      #     TEXTILE_ORG_API_SECRET: ${{ secrets.TEXTILE_ORG_API_SECRET }}
      #     TEXTILE_USER_API_SECRET: ${{  secrets.TEXTILE_USER_API_SECRET }}
      #     PROD_HOST: localhost

      ##### TEST PASSED -- BUILD STAGING IMAGES #####

      # - uses: mr-smithers-excellent/docker-build-push@v5
      #   name: Build & push Docker image - api
      #   with:
      #     image: eduvault/eduvault_api
      #     tags: staging
      #     registry: docker.io
      #     dockerfile: api/Dockerfile_prod
      #     directory: api
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image - app
        with:
          image: eduvault/eduvault_app
          tags: staging
          registry: docker.io
          dockerfile: app/Dockerfile_prod
          directory: app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: PROD_HOST=${{ secrets.STAGING_HOST }},TEST=1

      # - uses: mr-smithers-excellent/docker-build-push@v5
      #   name: Build & push Docker image - example
      #   with:
      #     image: eduvault/eduvault_example
      #     tags: staging
      #     registry: docker.io
      #     dockerfile: example/Dockerfile_prod
      #     directory: example
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     buildArgs: PROD_HOST=${{ secrets.STAGING_HOST }}

      # - uses: mr-smithers-excellent/docker-build-push@v5
      #   name: Build & push Docker image - home-page
      #   with:
      #     image: eduvault/eduvault_home-page
      #     tags: staging
      #     registry: docker.io
      #     dockerfile: home-page/Dockerfile_prod
      #     directory: home-page
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
